### ISSUE TITLE
Add outputVerbosity into configuration

### ISSUE THREAD

**Issue by DovydasNavickas** [reactway/scss-bundle#29]
Discussion from https://github.com/SimplrJS/scss-bundle/pull/28

>Maybe adding yet another configuration point, e.g. outputVerbosity would do?
>The CLI gets a bit cluttered, but I suppose if you're using all of the options, you either use the configuration file or consume scss-bundle via TypeScript either way.

**Comment by MartynasZilinskas** [comment]
PR: https://github.com/reactway/scss-bundle/pull/65
