### ISSUE TITLE
Upcoming new version

### ISSUE THREAD

**Issue by DovydasNavickas** [reactway/scss-bundle#64]
Hey everyone,

I see that there were a few PRs and issues coming up recently, so to give you a heads up, we have been working on an updated version of `scss-bundle`.

The will be a couple of changes:
* Naming conventions from `PascalCased` public (exported) variables to `camelCased` ones
* `BundleAll` method is removed, but we'll open an issue to track if anyone needs it (we never used it ourselves)
* TypeScript-like config files

PR changes that were made to previous version and will be incorporated in the rewrite:
* #60 Allow watch mode to be turned off via CLI by @michaelbromley
* #62 Add a --noWatch (-nw) flag to disable file watching via CLI or build script by @chrisobserved
* #63 Switch to pure JS Sass library from node-sass by @ospatil

PR changes that are outdated:
* #61 Update Readme: Remove incorrect '--watch' reference by @chrisobserved
The watch flag will actually enable watching 🎉 

The changes will land this week and it would be very nice to have some testing done by you guys 👍

**Comment by DovydasNavickas** [comment]
One other thing I forgot to mention:
As we consolidate all our open-source efforts under one hat, we've moved the repo to another GitHub account called ReactWay. This account hosts high-quality and actively supported projects of ours, thus `scss-bundle` will benefit from the move 👍

**Comment by MartynasZilinskas** [comment]
Newest version is published under `canary` tag :tada::
```sh
$ npm install scss-bundle@canary
```

If everything works fine after upgrading, leave us a reply in this issue, so we know that we didn't break anything.
