### ISSUE TITLE
Syntax error and 'use strict' not found after update (3.0.0)

### ISSUE THREAD

**Issue by shiftgeist** [reactway/scss-bundle#71]
**Descript your bug**
Errors after executing scss-bundle:

```
project/node_modules/.bin/scss-bundle: 1: project/node_modules/.bin/scss-bundle: use strict: not found
project/node_modules/.bin/scss-bundle: 2: project/node_modules/.bin/scss-bundle: Syntax error: word unexpected (expecting ")")
```

**To Reproduce**
1. `npx scss-bundle`

**Package version:** 3.0.0
**Node version:** v12.8.1
**OS:** Linux

**Comment by MartynasZilinskas** [comment]
Fix is already on the way. https://github.com/reactway/scss-bundle/pull/70. Thanks @savushkin for that.

**Comment by MartynasZilinskas** [comment]
[v3.0.1](https://www.npmjs.com/package/scss-bundle/v/3.0.1) is released 🎉. I am closing this issue, if it doesn't fix your problem, please re-open.
