### ISSUE TITLE
v3.0.1 "--c" flag disappeared.

### ISSUE THREAD

**Issue by damienwebdev** [reactway/scss-bundle#75]
**Describe the bug**
v2.5.1 has a `--c` flag which indicates to the CLI where the `config.json` file lives. This seems to have been remapped in v3.0.1 to `--p`. The issue with `--p` is that in the event you have multiple `config.json` files and they aren't stored in your project directory, this paradigm doesn't work.

**To Reproduce**
Create a project where config is stored in a different directory than `node_modules`. Try to utilize that config file from the CLI.

**Expected behavior**
I should be able to explicitly pass where my config file is located.

**Package version:** v3.0.1
**Node version:** v10.15.0
**OS:** MacOS

**Comment by literalpie** [comment]
it's strange the the --c flag isn't mentioned in the readme

**Comment by MartynasZilinskas** [comment]
I have published a canary version with `-c` option. Also added `project` property in `bundlerOptions`. 
Try it, and if it works, leave a comment we will close this issue and publish as normal version.
```
$ npm install scss-bundle@0.0.0-canary.9f111cb -D
```

**Comment by cmurczek** [comment]
I ran into the same issue as @damienwebdev. After installing the canary build @MartynasZilinskas mentioned, the -c flag is working again.

**Comment by manpuriasudip** [comment]
I am using 3.0.2 version and facing this issue. Is this resolved ?

**Comment by MartynasZilinskas** [comment]
@manpuriasudip I have released `v3.1.0` package with `--config` flag.
